import { defineField, defineType } from "sanity";

const text = (name: string, title: string) =>
  defineField({ name, title, type: "string" });

export const accountNavigation = defineType({
  name: "accountNavigation",
  title: "Account navigation",
  type: "document",
  initialValue: {
    ariaLabel: "Customer account",
    overviewLabel: "Overview",
    ordersLabel: "Orders",
    addressesLabel: "Addresses",
    profileLabel: "Profile",
    supportLabel: "Support",
    signOutLabel: "Sign out",
  },
  fields: [
    text("ariaLabel", "Navigation accessibility label"),
    text("overviewLabel", "Overview link"),
    text("ordersLabel", "Orders link"),
    text("addressesLabel", "Addresses link"),
    text("profileLabel", "Profile link"),
    text("supportLabel", "Support link"),
    text("signOutLabel", "Sign out link"),
  ],
});

export const accountLoginPage = defineType({
  name: "accountLoginPage",
  title: "Login page",
  type: "document",
  initialValue: {
    seoTitle: "Sign in | Ivory Muse",
    eyebrow: "Customer account",
    heading: "Welcome back",
    description:
      "Sign in to review your orders, manage addresses and continue your Ivory Muse experience.",
    emailLabel: "Email address",
    passwordLabel: "Password",
    rememberLabel: "Remember me",
    forgotPasswordLabel: "Forgot password?",
    submitLabel: "Sign in",
    submittingLabel: "Signing in…",
    newCustomerText: "New to Ivory Muse?",
    registerLinkLabel: "Create an account",
  },
  fields: [
    text("seoTitle", "SEO title"),
    text("eyebrow", "Eyebrow"),
    text("heading", "Heading"),
    defineField({
      name: "description",
      title: "Description",
      type: "text",
      rows: 3,
    }),
    text("emailLabel", "Email label"),
    text("passwordLabel", "Password label"),
    text("rememberLabel", "Remember me label"),
    text("forgotPasswordLabel", "Forgot password link"),
    text("submitLabel", "Submit button"),
    text("submittingLabel", "Submitting text"),
    text("newCustomerText", "New customer text"),
    text("registerLinkLabel", "Registration link"),
  ],
});

export const accountRegisterPage = defineType({
  name: "accountRegisterPage",
  title: "Registration page",
  type: "document",
  initialValue: {
    seoTitle: "Create account | Ivory Muse",
    eyebrow: "New customer",
    heading: "Create an account",
    description:
      "Keep your orders, delivery details and favourite pieces together in one considered space.",
    firstNameLabel: "First name",
    lastNameLabel: "Last name",
    emailLabel: "Email address",
    passwordLabel: "Password",
    passwordHint: "Use a secure password for your account",
    confirmPasswordLabel: "Confirm password",
    passwordStrengthLabel: "Password strength",
    strengthWeak: "Weak",
    strengthFair: "Fair",
    strengthGood: "Good",
    strengthStrong: "Strong",
    requirementLength: "8+ characters",
    requirementCase: "Upper & lowercase",
    requirementNumber: "One number",
    requirementSymbol: "One symbol",
    marketingLabel: "Email me about new collections and private offers",
    submitLabel: "Create account",
    submittingLabel: "Creating account…",
    existingCustomerText: "Already registered?",
    loginLinkLabel: "Sign in",
  },
  fields: [
    text("seoTitle", "SEO title"),
    text("eyebrow", "Eyebrow"),
    text("heading", "Heading"),
    defineField({
      name: "description",
      title: "Description",
      type: "text",
      rows: 3,
    }),
    text("firstNameLabel", "First name label"),
    text("lastNameLabel", "Last name label"),
    text("emailLabel", "Email label"),
    text("passwordLabel", "Password label"),
    text("passwordHint", "Password helper text"),
    text("confirmPasswordLabel", "Confirm password label"),
    text("passwordStrengthLabel", "Strength label"),
    text("strengthWeak", "Weak label"),
    text("strengthFair", "Fair label"),
    text("strengthGood", "Good label"),
    text("strengthStrong", "Strong label"),
    text("requirementLength", "Length requirement"),
    text("requirementCase", "Letter case requirement"),
    text("requirementNumber", "Number requirement"),
    text("requirementSymbol", "Symbol requirement"),
    text("marketingLabel", "Marketing consent label"),
    text("submitLabel", "Submit button"),
    text("submittingLabel", "Submitting text"),
    text("existingCustomerText", "Existing customer text"),
    text("loginLinkLabel", "Login link"),
  ],
});

export const accountRecoveryPage = defineType({
  name: "accountRecoveryPage",
  title: "Password recovery page",
  type: "document",
  initialValue: {
    seoTitle: "Reset password | Ivory Muse",
    eyebrow: "Account recovery",
    heading: "Reset your password",
    description: "Enter the email address used for your Ivory Muse account.",
    emailLabel: "Email address",
    submitLabel: "Send reset instructions",
    submittingLabel: "Sending…",
    backLabel: "Back to sign in",
  },
  fields: [
    text("seoTitle", "SEO title"),
    text("eyebrow", "Eyebrow"),
    text("heading", "Heading"),
    defineField({
      name: "description",
      title: "Description",
      type: "text",
      rows: 3,
    }),
    text("emailLabel", "Email label"),
    text("submitLabel", "Submit button"),
    text("submittingLabel", "Submitting text"),
    text("backLabel", "Back to login link"),
  ],
});

export const accountDashboardPage = defineType({
  name: "accountDashboardPage",
  title: "Dashboard page",
  type: "document",
  initialValue: {
    seoTitle: "My account | Ivory Muse",
    eyebrow: "My account",
    greetingPrefix: "Welcome back",
    intro: "Manage your orders, addresses and personal details in one place.",
    addressHeading: "Default address",
    noAddressText: "No address saved yet.",
    manageAddressesLabel: "Manage addresses",
    ordersHeading: "Recent orders",
    noOrdersText: "You have not placed an order yet.",
    viewOrdersLabel: "View all orders",
    profileCardTitle: "Personal details",
    profileCardText: "Keep your contact information and password up to date.",
    profileCardLabel: "Manage profile",
    supportCardTitle: "Need assistance?",
    supportCardText:
      "Our customer care team is here to help with orders and products.",
    supportCardLabel: "Contact us",
    shopLabel: "Continue shopping",
  },
  fields: [
    text("seoTitle", "SEO title"),
    text("eyebrow", "Eyebrow"),
    text("greetingPrefix", "Greeting prefix"),
    defineField({
      name: "intro",
      title: "Introduction",
      type: "text",
      rows: 2,
    }),
    text("addressHeading", "Default address heading"),
    text("noAddressText", "No address message"),
    text("manageAddressesLabel", "Manage addresses link"),
    text("ordersHeading", "Recent orders heading"),
    text("noOrdersText", "No orders message"),
    text("viewOrdersLabel", "View all orders link"),
    text("profileCardTitle", "Profile card title"),
    defineField({
      name: "profileCardText",
      title: "Profile card text",
      type: "text",
      rows: 2,
    }),
    text("profileCardLabel", "Profile card link"),
    text("supportCardTitle", "Support card title"),
    defineField({
      name: "supportCardText",
      title: "Support card text",
      type: "text",
      rows: 2,
    }),
    text("supportCardLabel", "Support card link"),
    text("shopLabel", "Continue shopping link"),
  ],
});

export const accountProfilePage = defineType({
  name: "accountProfilePage",
  title: "Profile page",
  type: "document",
  initialValue: {
    seoTitle: "Profile | Ivory Muse",
    eyebrow: "Personal details",
    heading: "Your profile",
    description:
      "Update the information associated with your customer account.",
    detailsHeading: "Contact information",
    securityHeading: "Password",
    firstNameLabel: "First name",
    lastNameLabel: "Last name",
    emailLabel: "Email address",
    phoneLabel: "Phone",
    countryCodeLabel: "Country code",
    marketingLabel: "Receive news about collections and private offers",
    passwordLabel: "New password",
    confirmPasswordLabel: "Confirm new password",
    passwordHint:
      "Leave blank to keep your current password. Use at least 8 characters.",
    saveDetailsLabel: "Save details",
    savePasswordLabel: "Update password",
    confirmDetailsMessage: "Save these changes to your profile?",
    confirmPasswordMessage:
      "Update your account password? You will use the new password next time you sign in.",
  },
  fields: [
    text("seoTitle", "SEO title"),
    text("eyebrow", "Eyebrow"),
    text("heading", "Heading"),
    defineField({
      name: "description",
      title: "Description",
      type: "text",
      rows: 2,
    }),
    text("detailsHeading", "Contact section heading"),
    text("securityHeading", "Password section heading"),
    text("firstNameLabel", "First name label"),
    text("lastNameLabel", "Last name label"),
    text("emailLabel", "Email label"),
    text("phoneLabel", "Phone label"),
    text("countryCodeLabel", "Country code selector label"),
    text("marketingLabel", "Marketing consent label"),
    text("passwordLabel", "New password label"),
    text("confirmPasswordLabel", "Confirm new password label"),
    text("passwordHint", "Password helper text"),
    text("saveDetailsLabel", "Save details button"),
    text("savePasswordLabel", "Save password button"),
    text("confirmDetailsMessage", "Profile update confirmation"),
    text("confirmPasswordMessage", "Password update confirmation"),
  ],
});

export const accountOrdersPage = defineType({
  name: "accountOrdersPage",
  title: "Orders page",
  type: "document",
  initialValue: {
    seoTitle: "Orders | Ivory Muse",
    eyebrow: "Order history",
    heading: "Your orders",
    emptyKicker: "Ivory Muse collection",
    emptyHeading: "Your order history is waiting",
    emptyText:
      "When you place an order, its details and delivery progress will appear here.",
    shopLabel: "Start shopping",
  },
  fields: [
    text("seoTitle", "SEO title"),
    text("eyebrow", "Eyebrow"),
    text("heading", "Heading"),
    text("emptyKicker", "Empty state eyebrow"),
    text("emptyHeading", "Empty state heading"),
    text("emptyText", "Empty state description"),
    text("shopLabel", "Start shopping button"),
  ],
});

export const accountOrderDetailsPage = defineType({
  name: "accountOrderDetailsPage",
  title: "Order details page",
  type: "document",
  initialValue: {
    backLabel: "Back to orders",
    eyebrow: "Order details",
    trackLabel: "Track order",
    quantityLabel: "Quantity",
    eachLabel: "each",
    subtotalLabel: "Subtotal",
    shippingLabel: "Shipping",
    taxLabel: "Tax",
    totalLabel: "Total",
    shippingAddressHeading: "Shipping address",
    billingAddressHeading: "Billing address",
  },
  fields: [
    text("backLabel", "Back link"),
    text("eyebrow", "Eyebrow"),
    text("trackLabel", "Track order button"),
    text("quantityLabel", "Quantity label"),
    text("eachLabel", "Each label"),
    text("subtotalLabel", "Subtotal label"),
    text("shippingLabel", "Shipping label"),
    text("taxLabel", "Tax label"),
    text("totalLabel", "Total label"),
    text("shippingAddressHeading", "Shipping address heading"),
    text("billingAddressHeading", "Billing address heading"),
  ],
});

export const accountAddressesPage = defineType({
  name: "accountAddressesPage",
  title: "Addresses page",
  type: "document",
  initialValue: {
    seoTitle: "Addresses | Ivory Muse",
    eyebrow: "Address book",
    heading: "Your addresses",
    defaultLabel: "Default",
    editLabel: "Edit",
    setDefaultLabel: "Set default",
    deleteLabel: "Delete",
    editHeading: "Edit address",
    addHeading: "Add a new address",
    firstNameLabel: "First name",
    lastNameLabel: "Last name",
    companyLabel: "Company",
    phoneLabel: "Phone",
    address1Label: "Address",
    address2Label: "Apartment, suite, etc.",
    cityLabel: "City",
    provinceLabel: "State / province",
    countryLabel: "Country",
    postalCodeLabel: "Postal code",
    defaultAddressLabel: "Set as default address",
    saveLabel: "Save changes",
    addLabel: "Add address",
    cancelLabel: "Cancel",
    confirmUpdateMessage: "Save these changes to your address?",
    confirmDefaultMessage: "Make this your default delivery address?",
    confirmDeleteMessage: "Delete this address? This action cannot be undone.",
  },
  fields: [
    text("seoTitle", "SEO title"),
    text("eyebrow", "Eyebrow"),
    text("heading", "Heading"),
    text("defaultLabel", "Default badge"),
    text("editLabel", "Edit button"),
    text("setDefaultLabel", "Set default button"),
    text("deleteLabel", "Delete button"),
    text("editHeading", "Edit form heading"),
    text("addHeading", "Add form heading"),
    text("firstNameLabel", "First name label"),
    text("lastNameLabel", "Last name label"),
    text("companyLabel", "Company label"),
    text("phoneLabel", "Phone label"),
    text("address1Label", "Address label"),
    text("address2Label", "Apartment label"),
    text("cityLabel", "City label"),
    text("provinceLabel", "State / province label"),
    text("countryLabel", "Country label"),
    text("postalCodeLabel", "Postal code label"),
    text("defaultAddressLabel", "Set as default checkbox"),
    text("saveLabel", "Save changes button"),
    text("addLabel", "Add address button"),
    text("cancelLabel", "Cancel button"),
    text("confirmUpdateMessage", "Update confirmation message"),
    text("confirmDefaultMessage", "Set default confirmation message"),
    text("confirmDeleteMessage", "Delete confirmation message"),
  ],
});
