import { homePage } from "./homePage";
import { aboutPage } from "./aboutPage";
import { page } from "./page";
import { siteSettings } from "./siteSettings";
import { headerSettings } from "./headerSettings";
import { footerSettings } from "./footerSettings";
import { productPage } from "./productPage";
import { collectionPage } from "./collectionPage";
import { faqPage } from "./faqPage";
import { contactPage } from "./contactPage";
export const schemaTypes = [siteSettings, headerSettings, footerSettings, homePage, aboutPage, collectionPage, productPage, faqPage, contactPage, page];
