import { defineArrayMember, defineField, defineType } from "sanity";

export const productPage = defineType({
  name: "productPage",
  title: "Product page",
  type: "document",
  fields: [
    defineField({ name: "title", type: "string", initialValue: "Product page" }),
    defineField({
      name: "sections",
      title: "Page sections",
      type: "array",
      validation: (rule) => rule.max(2),
      of: [
        defineArrayMember({
          name: "productDetailsSettings",
          title: "Product details settings",
          type: "object",
          fields: [
            defineField({ name: "homeLabel", title: "Breadcrumb home label", type: "string", initialValue: "Home" }),
            defineField({ name: "homeHref", title: "Breadcrumb home link", type: "string", initialValue: "/" }),
            defineField({ name: "collectionLabel", title: "Breadcrumb collection label", type: "string", initialValue: "Collections" }),
            defineField({ name: "collectionHref", title: "Breadcrumb collection link", type: "string", initialValue: "/collections/shop" }),
            defineField({ name: "perUnitLabel", title: "Price unit label", type: "string", initialValue: "per metre" }),
            defineField({ name: "quantityLabel", title: "Quantity label", type: "string" }),
            defineField({ name: "totalLabel", title: "Total label", type: "string" }),
            defineField({ name: "minimumPurchaseText", title: "Minimum purchase note", type: "string" }),
            defineField({ name: "buyNowLabel", title: "Buy now button", type: "string" }),
            defineField({ name: "addToCartLabel", title: "Add to cart button", type: "string" }),
            defineField({ name: "purchaseSampleLabel", title: "Purchase sample button", type: "string" }),
            defineField({
              name: "sampleProductHandle",
              title: "Sample product handle",
              description: "Shopify handle of the shared sample product used on every product page.",
              type: "string",
              initialValue: "sample-proudct",
              validation: (rule) => rule.regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/, { name: "Shopify product handle" }),
            }),
            defineField({ name: "purchaseSampleHref", title: "Purchase sample link", type: "string" }),
            defineField({ name: "shippingText", title: "Shipping message", type: "string" }),
            defineField({ name: "sampleDetailsHeading", title: "Sample details heading", type: "string", initialValue: "Sample details" }),
            defineField({ name: "sampleShippingNote", title: "Sample price note", type: "string", initialValue: "$3 AUD per sample, excluding shipping" }),
            defineField({ name: "sampleSizeText", title: "Sample size", type: "string", initialValue: "Sample size is 10cm x 15cm" }),
            defineField({ name: "selectedLabel", title: "Selected variant label", type: "string", initialValue: "Selected" }),
            defineField({ name: "unavailableText", title: "Unavailable combination message", type: "string", initialValue: "This combination is unavailable." }),
            defineField({ name: "outOfStockText", title: "Out-of-stock label", type: "string", initialValue: "Out of stock" }),
            defineField({ name: "actionErrorText", title: "Cart error message", type: "string", initialValue: "Please try again." }),
            defineField({ name: "sampleErrorText", title: "Sample error message", type: "string", initialValue: "This sample is already in your cart, or the 10-sample limit has been reached." }),
            defineField({ name: "zoomLabel", title: "Image zoom label", type: "string", initialValue: "Click to zoom" }),
            defineField({ name: "specificationsHeading", title: "Specifications heading", type: "string" }),
            defineField({ name: "compositionLabel", title: "Composition label", type: "string" }),
            defineField({ name: "weightLabel", title: "Weight label", type: "string" }),
            defineField({ name: "widthLabel", title: "Width label", type: "string" }),
            defineField({ name: "careLabel", title: "Care label", type: "string" }),
          ],
          preview: { prepare: () => ({ title: "Product details settings", subtitle: "Labels, buttons, shipping and specifications" }) },
        }),
        defineArrayMember({
          name: "relatedProductsSettings",
          title: "Related products settings",
          type: "object",
          fields: [
            defineField({ name: "heading", title: "Heading", type: "string", initialValue: "CURATED SELECTION" }),
            defineField({ name: "productLimit", title: "Number of products", type: "number", initialValue: 4, validation: (rule) => rule.min(1).max(8).integer() }),
          ],
          preview: { select: { title: "heading" }, prepare: ({ title }) => ({ title: title || "Curated selection", subtitle: "Shopify recommendations" }) },
        }),
      ],
    }),
  ],
});
