import { defineField, defineType } from "sanity";

const text = (name: string, title: string, initialValue: string) =>
  defineField({ name, title, type: "string", initialValue });

export const storefrontContent = defineType({
  name: "storefrontContent",
  title: "Storefront utility content",
  type: "document",
  fields: [
    defineField({
      name: "searchPage",
      title: "Search page",
      type: "object",
      options: { collapsible: true, collapsed: false },
      fields: [
        text("seoTitle", "SEO title", "Search"),
        text("eyebrow", "Eyebrow", "Discover Ivory Muse"),
        text("heading", "Heading", "Search our collection"),
        text("intro", "Introduction", "Find silk fabrics by name, finish, colour or intended use."),
        text("inputLabel", "Search input label", "Search products"),
        text("placeholder", "Search placeholder", "What are you looking for?"),
        text("submitLabel", "Search button", "Search"),
        text("singleResultLabel", "Single result label", "result"),
        text("multipleResultsLabel", "Multiple results label", "results"),
        text("resultsForLabel", "Results query connector", "for"),
        text("resultsSuffix", "Results suffix", "Explore the matching collection below"),
        text("noResultsHeading", "No-results heading", "No products found"),
        text("noResultsText", "No-results message", "Try a different product name, colour or fabric type."),
        text("emptyHeading", "Empty-search heading", "Find your perfect silk"),
        text("emptyText", "Empty-search message", "Enter a search term to explore the Ivory Muse collection."),
      ],
    }),
    defineField({
      name: "cartPage",
      title: "Shopping bag page",
      type: "object",
      options: { collapsible: true, collapsed: true },
      fields: [
        text("seoTitle", "SEO title", "Shopping bag | Ivory Muse"),
        text("seoDescription", "SEO description", "Review your Ivory Muse selection and continue to secure checkout."),
        text("loadingText", "Loading message", "Preparing your shopping bag…"),
        text("itemsHeading", "Items heading", "Your pieces"),
        text("singleItemLabel", "Single item label", "item"),
        text("multipleItemsLabel", "Multiple items label", "items"),
        text("quantityLabel", "Quantity label", "Quantity"),
        text("summaryEyebrow", "Summary eyebrow", "Order summary"),
        text("summaryHeading", "Summary heading", "Summary"),
        text("subtotalLabel", "Subtotal label", "Subtotal"),
        text("shippingLabel", "Shipping label", "Shipping"),
        text("shippingValue", "Shipping value", "Calculated at checkout"),
        text("totalLabel", "Estimated total label", "Estimated total"),
        text("taxNote", "Tax and delivery note", "Taxes and delivery options are calculated securely at checkout."),
        text("checkoutLabel", "Checkout button", "Secure checkout"),
        text("checkoutLoadingLabel", "Checkout loading text", "Preparing checkout…"),
        text("secureNote", "Security note", "Secure checkout powered by Shopify"),
        text("emptyEyebrow", "Empty-bag eyebrow", "Your collection awaits"),
        text("emptyHeading", "Empty-bag heading", "Your shopping bag is empty"),
        text("emptyText", "Empty-bag message", "Discover considered silks selected for timeless garments and interiors."),
        text("continueLabel", "Continue shopping button", "Continue shopping"),
      ],
    }),
    defineField({
      name: "notFoundPage",
      title: "404 page",
      type: "object",
      options: { collapsible: true, collapsed: true },
      fields: [
        text("eyebrow", "Eyebrow", "Page not found"),
        text("heading", "Heading", "This page is unavailable"),
        text("message", "Message", "The page may have moved or no longer exists."),
        text("homeLabel", "Home button", "Return home"),
        text("shopLabel", "Shop button", "Shop silks"),
      ],
    }),
    defineField({
      name: "previewLoginPage",
      title: "Private preview login page",
      type: "object",
      options: { collapsible: true, collapsed: true },
      fields: [
        text("seoTitle", "SEO title", "Private Preview"),
        text("logoFallback", "Logo text fallback", "IVORY MUSE"),
        text("eyebrow", "Eyebrow", "Private website preview"),
        text("heading", "Heading", "Welcome to Ivory Muse"),
        text("intro", "Introduction", "Please enter the preview credentials provided to you."),
        text("usernameLabel", "Username label", "Username"),
        text("passwordLabel", "Password label", "Password"),
        text("submitLabel", "Submit button", "Enter preview"),
        text("submittingLabel", "Submitting text", "Signing in…"),
        text("fallbackError", "Fallback error message", "Please try again."),
      ],
    }),
  ],
});
