"use client";
import type { SanityImageSource } from "@sanity/image-url";
import Image from "next/image";
import Link from "next/link";
import {ChevronLeft,ChevronRight} from "lucide-react";
import useEmblaCarousel from "embla-carousel-react";
import Autoplay from "embla-carousel-autoplay";
import {sanityImageUrl} from "@/sanity/lib/image";
export type EditorialCard={_key?:string;title?:string;description?:string;image?:SanityImageSource;linkLabel?:string;linkHref?:string};
export function EditorialSlider({cards}:{cards:EditorialCard[]}){const[ref,api]=useEmblaCarousel({loop:cards.length>3,align:"start"},[Autoplay({delay:4800,stopOnInteraction:true})]);return <div className="relative"><div ref={ref} className="overflow-hidden"><div className="-ml-5 flex">{cards.map((c,i)=><article key={c._key||i} className="min-w-0 flex-[0_0_88%] pl-5 sm:flex-[0_0_50%] lg:flex-[0_0_33.333%]"><div className="h-full bg-[var(--surface)] p-5 text-center">{c.image&&<div className="relative aspect-[.78] overflow-hidden"><Image fill src={sanityImageUrl(c.image,900)} alt={c.title||""} className="object-cover" sizes="(min-width:1024px) 31vw, 84vw"/></div>}{c.title&&<h3 className="mt-6 font-heading text-2xl text-[var(--accent)]">{c.title}</h3>}{c.description&&<p className="mx-auto mt-3 max-w-sm text-[11px] leading-5">{c.description}</p>}{c.linkHref&&c.linkLabel&&<Link className="mt-4 inline-block text-[10px] underline underline-offset-4" href={c.linkHref}>{c.linkLabel}</Link>}</div></article>)}</div></div>{cards.length>1&&<><button aria-label="Previous slide" onClick={()=>api?.scrollPrev()} className="absolute left-0 top-1/2 flex size-10 -translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full bg-[var(--accent)] text-white shadow-md"><ChevronLeft size={18}/></button><button aria-label="Next slide" onClick={()=>api?.scrollNext()} className="absolute right-0 top-1/2 flex size-10 translate-x-1/2 -translate-y-1/2 items-center justify-center rounded-full bg-[var(--accent)] text-white shadow-md"><ChevronRight size={18}/></button></>}</div>}
