"use server";
import { cookies } from "next/headers";
import { redirect } from "next/navigation";
import { storefrontCustomerFetch } from "@/lib/customer-account/client";
import { CUSTOMER_SESSION_COOKIE, customerCookieOptions, encryptSession } from "@/lib/customer-account/session";

export type AuthState={error?:string;success?:string};
type TokenPayload={customerAccessTokenCreate:{customerAccessToken?:{accessToken:string;expiresAt:string};customerUserErrors:Array<{message:string}>}};
const TOKEN_MUTATION=`mutation Login($input:CustomerAccessTokenCreateInput!){customerAccessTokenCreate(input:$input){customerAccessToken{accessToken expiresAt}customerUserErrors{message}}}`;
async function createSession(email:string,password:string){const data=await storefrontCustomerFetch<TokenPayload>(TOKEN_MUTATION,{input:{email,password}});const result=data.customerAccessTokenCreate;if(!result.customerAccessToken)throw new Error(result.customerUserErrors[0]?.message||"Email or password is incorrect.");const expiresAt=new Date(result.customerAccessToken.expiresAt).getTime();(await cookies()).set(CUSTOMER_SESSION_COOKIE,encryptSession({accessToken:result.customerAccessToken.accessToken,expiresAt}),{...customerCookieOptions,expires:new Date(expiresAt)});}

export async function loginAction(_state:AuthState,formData:FormData):Promise<AuthState>{const email=String(formData.get("email")||"").trim().toLowerCase();const password=String(formData.get("password")||"");if(!email||!password)return{error:"Enter your email and password."};try{await createSession(email,password);}catch(error){return{error:error instanceof Error?error.message:"Sign in failed."}}redirect("/account");}

export async function registerAction(_state:AuthState,formData:FormData):Promise<AuthState>{const firstName=String(formData.get("firstName")||"").trim();const lastName=String(formData.get("lastName")||"").trim();const email=String(formData.get("email")||"").trim().toLowerCase();const password=String(formData.get("password")||"");const confirm=String(formData.get("confirmPassword")||"");if(!firstName||!lastName||!email)return{error:"Complete all required fields."};if(password.length<8)return{error:"Password must contain at least 8 characters."};if(password!==confirm)return{error:"Passwords do not match."};try{const data=await storefrontCustomerFetch<{customerCreate:{customer?:{id:string};customerUserErrors:Array<{message:string}>}}>(`mutation Register($input:CustomerCreateInput!){customerCreate(input:$input){customer{id}customerUserErrors{message}}}`,{input:{firstName,lastName,email,password,acceptsMarketing:formData.get("acceptsMarketing")==="on"}});const result=data.customerCreate;if(!result.customer)throw new Error(result.customerUserErrors[0]?.message||"Account could not be created.");await createSession(email,password);}catch(error){return{error:error instanceof Error?error.message:"Registration failed."}}redirect("/account");}

export async function recoverAction(_state:AuthState,formData:FormData):Promise<AuthState>{const email=String(formData.get("email")||"").trim().toLowerCase();if(!email)return{error:"Enter your email address."};try{const data=await storefrontCustomerFetch<{customerRecover:{customerUserErrors:Array<{message:string}>}}>(`mutation Recover($email:String!){customerRecover(email:$email){customerUserErrors{message}}}`,{email});const error=data.customerRecover.customerUserErrors[0];if(error)return{error:error.message};return{success:"If an account exists for this email, Shopify has sent password reset instructions."};}catch{return{error:"Password reset could not be requested. Please try again."}}}
