"use server";
import {revalidatePath} from "next/cache";import {redirect} from "next/navigation";import {customerAccountFetch,decodeCustomerId} from "@/lib/customer-account/client";
const fields=["firstName","lastName","company","address1","address2","city","province","country","zip","phone"] as const;
const countryDialCodes:Record<string,string>={australia:"61",au:"61",bangladesh:"880",bd:"880",india:"91",in:"91","new zealand":"64",nz:"64","united kingdom":"44",uk:"44",gb:"44","united states":"1",usa:"1",us:"1",canada:"1",ca:"1"};
const normalizePhone=(phone:string,country:string)=>{const value=phone.trim();if(!value)return "";const digits=value.replace(/\D/g,"");if(value.startsWith("+"))return `+${digits}`;if(digits.startsWith("00"))return `+${digits.slice(2)}`;const dialCode=countryDialCodes[country.trim().toLowerCase()];if(!dialCode)return value;if(digits.startsWith(dialCode)&&digits.length>dialCode.length+6)return `+${digits}`;const nationalNumber=digits.replace(/^0+/,"");return nationalNumber?`+${dialCode}${nationalNumber}`:"";};
const addressFrom=(formData:FormData)=>{const country=String(formData.get("country")||"").trim();return Object.fromEntries(fields.map(field=>{const value=String(formData.get(field)||"").trim();return [field,field==="phone"?normalizePhone(value,country):value];}).filter(([,value])=>value));};
const destination=(type:"success"|"error",value:string)=>`/account/addresses?${type}=${encodeURIComponent(value)}`;const errorMessage=(error:unknown)=>error instanceof Error?error.message:"Address could not be saved";
async function makeDefault(addressId:string){return customerAccountFetch<{customerDefaultAddressUpdate:{customerUserErrors:Array<{message:string}>}}>(`mutation Default($customerAccessToken:String!,$addressId:ID!){customerDefaultAddressUpdate(customerAccessToken:$customerAccessToken,addressId:$addressId){customerUserErrors{message}}}`,{addressId});}
export async function saveAddress(formData:FormData){const encodedId=String(formData.get("id")||"");const address=addressFrom(formData);const defaultAddress=formData.get("defaultAddress")==="on";if(!address.address1||!address.city||!address.country||!address.zip)redirect(destination("error","Address, city, country and postal code are required."));let next:string;try{if(encodedId){const addressId=decodeCustomerId(encodedId);const data=await customerAccountFetch<{customerAddressUpdate:{customerUserErrors:Array<{message:string}>}}>(`mutation Update($customerAccessToken:String!,$addressId:ID!,$address:MailingAddressInput!){customerAddressUpdate(customerAccessToken:$customerAccessToken,id:$addressId,address:$address){customerUserErrors{message}}}`,{addressId,address});const error=data.customerAddressUpdate.customerUserErrors[0];if(!error&&defaultAddress)await makeDefault(addressId);next=error?destination("error",error.message):destination("success","Address updated.");}else{const data=await customerAccountFetch<{customerAddressCreate:{customerAddress?:{id:string};customerUserErrors:Array<{message:string}>}}>(`mutation Create($customerAccessToken:String!,$address:MailingAddressInput!){customerAddressCreate(customerAccessToken:$customerAccessToken,address:$address){customerAddress{id}customerUserErrors{message}}}`,{address});const result=data.customerAddressCreate;const error=result.customerUserErrors[0];if(!error&&defaultAddress&&result.customerAddress)await makeDefault(result.customerAddress.id);next=error?destination("error",error.message):destination("success","Address added.");}}catch(error){next=destination("error",errorMessage(error));}revalidatePath("/account");revalidatePath("/account/addresses");redirect(next);}
export async function deleteAddress(formData:FormData){let next:string;try{const addressId=decodeCustomerId(String(formData.get("id")||""));const data=await customerAccountFetch<{customerAddressDelete:{customerUserErrors:Array<{message:string}>}}>(`mutation Delete($customerAccessToken:String!,$addressId:ID!){customerAddressDelete(customerAccessToken:$customerAccessToken,id:$addressId){customerUserErrors{message}}}`,{addressId});const error=data.customerAddressDelete.customerUserErrors[0];next=error?destination("error",error.message):destination("success","Address deleted.");}catch(error){next=destination("error",errorMessage(error));}revalidatePath("/account");revalidatePath("/account/addresses");redirect(next);}
export async function setDefaultAddress(formData:FormData){let next:string;try{const addressId=decodeCustomerId(String(formData.get("id")||""));const data=await makeDefault(addressId);const error=data.customerDefaultAddressUpdate.customerUserErrors[0];next=error?destination("error",error.message):destination("success","Default address updated.");}catch(error){next=destination("error",errorMessage(error));}revalidatePath("/account");revalidatePath("/account/addresses");redirect(next);}
