"use server";
import {revalidatePath} from "next/cache";import {redirect} from "next/navigation";import {customerAccountFetch,decodeCustomerId} from "@/lib/customer-account/client";
const fields=["firstName","lastName","company","address1","address2","city","province","country","zip","phone"] as const;
const addressFrom=(formData:FormData)=>Object.fromEntries(fields.map(field=>[field,String(formData.get(field)||"").trim()]).filter(([,value])=>value));
const destination=(type:"success"|"error",value:string)=>`/account/addresses?${type}=${encodeURIComponent(value)}`;const errorMessage=(error:unknown)=>error instanceof Error?error.message:"Address could not be saved";
async function makeDefault(addressId:string){return customerAccountFetch<{customerDefaultAddressUpdate:{customerUserErrors:Array<{message:string}>}}>(`mutation Default($customerAccessToken:String!,$addressId:ID!){customerDefaultAddressUpdate(customerAccessToken:$customerAccessToken,addressId:$addressId){customerUserErrors{message}}}`,{addressId});}
export async function saveAddress(formData:FormData){const encodedId=String(formData.get("id")||"");const address=addressFrom(formData);const defaultAddress=formData.get("defaultAddress")==="on";if(!address.address1||!address.city||!address.country||!address.zip)redirect(destination("error","Address, city, country and postal code are required."));let next:string;try{if(encodedId){const addressId=decodeCustomerId(encodedId);const data=await customerAccountFetch<{customerAddressUpdate:{customerUserErrors:Array<{message:string}>}}>(`mutation Update($customerAccessToken:String!,$addressId:ID!,$address:MailingAddressInput!){customerAddressUpdate(customerAccessToken:$customerAccessToken,id:$addressId,address:$address){customerUserErrors{message}}}`,{addressId,address});const error=data.customerAddressUpdate.customerUserErrors[0];if(!error&&defaultAddress)await makeDefault(addressId);next=error?destination("error",error.message):destination("success","Address updated.");}else{const data=await customerAccountFetch<{customerAddressCreate:{customerAddress?:{id:string};customerUserErrors:Array<{message:string}>}}>(`mutation Create($customerAccessToken:String!,$address:MailingAddressInput!){customerAddressCreate(customerAccessToken:$customerAccessToken,address:$address){customerAddress{id}customerUserErrors{message}}}`,{address});const result=data.customerAddressCreate;const error=result.customerUserErrors[0];if(!error&&defaultAddress&&result.customerAddress)await makeDefault(result.customerAddress.id);next=error?destination("error",error.message):destination("success","Address added.");}}catch(error){next=destination("error",errorMessage(error));}revalidatePath("/account");revalidatePath("/account/addresses");redirect(next);}
export async function deleteAddress(formData:FormData){let next:string;try{const addressId=decodeCustomerId(String(formData.get("id")||""));const data=await customerAccountFetch<{customerAddressDelete:{customerUserErrors:Array<{message:string}>}}>(`mutation Delete($customerAccessToken:String!,$addressId:ID!){customerAddressDelete(customerAccessToken:$customerAccessToken,id:$addressId){customerUserErrors{message}}}`,{addressId});const error=data.customerAddressDelete.customerUserErrors[0];next=error?destination("error",error.message):destination("success","Address deleted.");}catch(error){next=destination("error",errorMessage(error));}revalidatePath("/account");revalidatePath("/account/addresses");redirect(next);}
export async function setDefaultAddress(formData:FormData){let next:string;try{const addressId=decodeCustomerId(String(formData.get("id")||""));const data=await makeDefault(addressId);const error=data.customerDefaultAddressUpdate.customerUserErrors[0];next=error?destination("error",error.message):destination("success","Default address updated.");}catch(error){next=destination("error",errorMessage(error));}revalidatePath("/account");revalidatePath("/account/addresses");redirect(next);}
