"use server";
import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";
import { customerAccountFetch, decodeCustomerId } from "@/lib/customer-account/client";

type Result = { userErrors: Array<{ message: string }> };
const countryCodes: Record<string, string> = { australia: "AU", au: "AU", bangladesh: "BD", bd: "BD", india: "IN", in: "IN", "new zealand": "NZ", nz: "NZ", "united kingdom": "GB", uk: "GB", gb: "GB", "united states": "US", usa: "US", us: "US", canada: "CA", ca: "CA" };
const dialCodes: Record<string, string> = { AU: "61", BD: "880", IN: "91", NZ: "64", GB: "44", US: "1", CA: "1" };
const addressFrom = (formData: FormData) => { const value = (name: string) => String(formData.get(name) || "").trim(); const country = value("country") || "Australia"; const territoryCode = countryCodes[country.toLowerCase()] || country.toUpperCase(); const rawPhone = value("phone"); const digits = rawPhone.replace(/\D/g, ""); const phoneNumber = rawPhone ? (rawPhone.startsWith("+") ? `+${digits}` : dialCodes[territoryCode] ? `+${dialCodes[territoryCode]}${digits.replace(/^0+/, "")}` : rawPhone) : ""; return { firstName: value("firstName"), lastName: value("lastName"), company: value("company"), address1: value("address1"), address2: value("address2"), city: value("city"), zoneCode: value("province"), territoryCode, zip: value("zip"), phoneNumber }; };
const destination = (type: "success" | "error", value: string) => `/account/addresses?${type}=${encodeURIComponent(value)}`;
const message = (error: unknown) => error instanceof Error ? error.message : "Address could not be saved";
const finish = () => { revalidatePath("/account"); revalidatePath("/account/addresses"); };

export async function saveAddress(formData: FormData) { const encodedId = String(formData.get("id") || ""); const address = addressFrom(formData); const defaultAddress = formData.get("defaultAddress") === "on"; if (!address.address1 || !address.city || !address.territoryCode || !address.zip) redirect(destination("error", "Address, city, country and postal code are required.")); let next: string; try { if (encodedId) { const data = await customerAccountFetch<{ customerAddressUpdate: Result }>(`mutation Update($addressId: ID!, $address: CustomerAddressInput!, $defaultAddress: Boolean) { customerAddressUpdate(addressId: $addressId, address: $address, defaultAddress: $defaultAddress) { userErrors { message } } }`, { addressId: decodeCustomerId(encodedId), address, defaultAddress }); const error = data.customerAddressUpdate.userErrors[0]; next = error ? destination("error", error.message) : destination("success", "Address updated."); } else { const data = await customerAccountFetch<{ customerAddressCreate: Result }>(`mutation Create($address: CustomerAddressInput!, $defaultAddress: Boolean) { customerAddressCreate(address: $address, defaultAddress: $defaultAddress) { userErrors { message } } }`, { address, defaultAddress }); const error = data.customerAddressCreate.userErrors[0]; next = error ? destination("error", error.message) : destination("success", "Address added."); } } catch (error) { next = destination("error", message(error)); } finish(); redirect(next); }
export async function deleteAddress(formData: FormData) { let next: string; try { const data = await customerAccountFetch<{ customerAddressDelete: Result }>(`mutation Delete($addressId: ID!) { customerAddressDelete(addressId: $addressId) { userErrors { message } } }`, { addressId: decodeCustomerId(String(formData.get("id") || "")) }); const error = data.customerAddressDelete.userErrors[0]; next = error ? destination("error", error.message) : destination("success", "Address deleted."); } catch (error) { next = destination("error", message(error)); } finish(); redirect(next); }
export async function setDefaultAddress(formData: FormData) { let next: string; try { const data = await customerAccountFetch<{ customerAddressUpdate: Result }>(`mutation Default($addressId: ID!) { customerAddressUpdate(addressId: $addressId, defaultAddress: true) { userErrors { message } } }`, { addressId: decodeCustomerId(String(formData.get("id") || "")) }); const error = data.customerAddressUpdate.userErrors[0]; next = error ? destination("error", error.message) : destination("success", "Default address updated."); } catch (error) { next = destination("error", message(error)); } finish(); redirect(next); }
